# Generated by Django 4.2.16 on 2024-10-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email_contato_2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
