# Generated by Django 4.2.16 on 2024-11-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email_contato_1',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email_contato_2',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone_contato_1',
            field=models.CharField(max_length=26),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone_contato_2',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
